name: go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: test
      shell: bash
      env:
        CLIENT_ID: ${{ secrets.DOTS_CLIENT_ID }}
        API_KEY: ${{ secrets.DOTS_API_KEY }}
      run: |
        export DOTS_CLIENT_ID="$CLIENT_ID" && export DOTS_API_KEY="$API_KEY" &&  go test -v ./...